### ISSUE TITLE
Webpack integration?

### ISSUE THREAD

**Issue by milgner** [jostylr/literate-programming-lib#3]
Are you aware of any integration of this lib into webpack? I'd really like to use literate programming but am wondering how to best integrate it into my build pipeline. Manually watching JS files feels a bit cumbersome and I think the best way would be to integrate the library with webpack in order to also generate/keep source maps. Unfortunately this is also my first project using webpack and I'm not sure how to best integrate it there...

Any ideas?

**Comment by jostylr** [comment]
I know of no integrations into webpack nor have I used that. It looks like an interesting direction and I'll keep this open to investigate. 

I am not sure what you mean by "manually watching JS files". The literate-programming files can be monitored and automatically compiled with something like nodemon (I've done that at times) and it can output whatever resources you want wherever they go. 

Source maps would be great, but I don't know how easy that would be nor do I use source maps as much of my code is written as is and so a quick search with a snippet usually gets me right to where I need to go.

**Comment by pcardune** [comment]
I would be interested in a webpack loader for literate javascript files as well. If I get around to writing one on my own, I'll be sure to send a pull request.
